from dataset_tuning import train_loader, test_loader, val_loader
#Let’s examine the dimensions of the input and target batches generated by the training loader:

print("\nTrain loader: <enter>")
input()

for inputs, targets in train_loader:
    print(inputs.shape, targets.shape)

'''
The output is as follows (truncated to conserve space):

Train loader:
torch.Size([8, 61]) torch.Size([8, 61])
torch.Size([8, 76]) torch.Size([8, 76])
torch.Size([8, 73]) torch.Size([8, 73])
...
torch.Size([8, 74]) torch.Size([8, 74])
torch.Size([8, 69]) torch.Size([8, 69])
'''

print("\nTest loader: <enter>")
input()

for inputs, targets in test_loader:
    print(inputs.shape, targets.shape)


print("\nValidation loader: <enter>")
input()

for inputs, targets in val_loader:
    print(inputs.shape, targets.shape)




